### ISSUE TITLE
[question] What exactly is SpellCheckJs, and why am I invited to join

### ISSUE THREAD

**Issue by MystPi** [SpellCheckJS/SpellCheckJS#11]
^

**Comment by MystPi** [comment]
```python
print("Hello, world!")
```

**Comment by MystPi** [comment]
```python
print("Hello, world!")
```

**Comment by hello-smile6** [comment]
> ^

It's a project for creating a list of common mispellings for words.

**Comment by MystPi** [comment]
> > ^
> 
> It's a project for creating a list of common mispellings for words.

Oh.

**Comment by hello-smile6** [comment]
> > > ^
> > 
> > 
> > It's a project for creating a list of common mispellings for words.
> 
> Oh.

I removed your invite. If you want me to do it again, just ask.

**Comment by hello-smile6** [comment]
> > > ^
> > 
> > 
> > It's a project for creating a list of common mispellings for words.
> 
> Oh. You should add "mispellings" to the list then. 🤣

You could. Just edit https://github.com/SpellCheckJS/SpellCheckJS/blob/main/spellcheck.json and make a PR. Just add a new key to the object, with the key being the incorrect version and the value being the correct version.

**Comment by hello-smile6** [comment]
> > > ^
> > 
> > 
> > It's a project for creating a list of common mispellings for words.
> 
> Oh. You should add "mispellings" to the list then. 🤣

Added in 776a62a7055df0af57e7409d8161787dcb7455e2
